/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnderWaterRouteImport } from './routes/onder-water'
import { Route as SimuleerRouteImport } from './routes/simuleer'
import { Route as WerkdagRouteImport } from './routes/werkdag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnderWaterRoute = OnderWaterRouteImport.update({
  id: '/onder-water',
  path: '/onder-water',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuleerRoute = SimuleerRouteImport.update({
  id: '/simuleer',
  path: '/simuleer',
  getParentRoute: () => rootRouteImport,
} as any)
const WerkdagRoute = WerkdagRouteImport.update({
  id: '/werkdag',
  path: '/werkdag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onder-water': typeof OnderWaterRoute
  '/simuleer': typeof SimuleerRoute
  '/werkdag': typeof WerkdagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onder-water': typeof OnderWaterRoute
  '/simuleer': typeof SimuleerRoute
  '/werkdag': typeof WerkdagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onder-water': typeof OnderWaterRoute
  '/simuleer': typeof SimuleerRoute
  '/werkdag': typeof WerkdagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/onder-water' | '/simuleer' | '/werkdag'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/onder-water' | '/simuleer' | '/werkdag'
  id: '__root__' | '/' | '/onder-water' | '/simuleer' | '/werkdag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnderWaterRoute: typeof OnderWaterRoute
  SimuleerRoute: typeof SimuleerRoute
  WerkdagRoute: typeof WerkdagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onder-water': {
      id: '/onder-water'
      path: '/onder-water'
      fullPath: '/onder-water'
      preLoaderRoute: typeof OnderWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simuleer': {
      id: '/simuleer'
      path: '/simuleer'
      fullPath: '/simuleer'
      preLoaderRoute: typeof SimuleerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werkdag': {
      id: '/werkdag'
      path: '/werkdag'
      fullPath: '/werkdag'
      preLoaderRoute: typeof WerkdagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnderWaterRoute: OnderWaterRoute,
  SimuleerRoute: SimuleerRoute,
  WerkdagRoute: WerkdagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
